-- Add sample products for testing the product catalog system
-- These products will be used to demonstrate the ecommerce functionality

-- Sample Electronics Products
INSERT INTO public.products (
  id, name, description, price, original_price, category, subcategory, brand, 
  main_image, stock_quantity, sku, tags, rating, review_count, is_featured, is_active, vendor_id, created_at, updated_at
) VALUES 
-- Electronics
(
  gen_random_uuid(), 
  'iPhone 15 Pro Max', 
  'Latest iPhone with A17 Pro chip, 48MP camera, and titanium design. Perfect for photography and gaming.',
  189999, 
  199999, 
  'Electronics', 
  'Smartphones', 
  'Apple', 
  '/placeholder.svg', 
  25, 
  'IPH15PM-256', 
  ARRAY['smartphone', 'camera', 'gaming', 'premium'], 
  4.8, 
  156, 
  true, 
  true, 
  (SELECT id FROM public.profiles WHERE role = 'admin' LIMIT 1), 
  NOW(), 
  NOW()
),
(
  gen_random_uuid(), 
  'Samsung Galaxy S24 Ultra', 
  'Premium Android flagship with S Pen, 200MP camera, and AI features. Ultimate productivity device.',
  179999, 
  189999, 
  'Electronics', 
  'Smartphones', 
  'Samsung', 
  '/placeholder.svg', 
  18, 
  'SGS24U-512', 
  ARRAY['smartphone', 's-pen', 'camera', 'productivity'], 
  4.7, 
  89, 
  true, 
  true, 
  (SELECT id FROM public.profiles WHERE role = 'admin' LIMIT 1), 
  NOW(), 
  NOW()
),
(
  gen_random_uuid(), 
  'MacBook Air M3', 
  'Ultra-thin laptop with M3 chip, 18-hour battery life, and stunning Retina display. Perfect for work and creativity.',
  249999, 
  269999, 
  'Electronics', 
  'Laptops', 
  'Apple', 
  '/placeholder.svg', 
  12, 
  'MBA-M3-256', 
  ARRAY['laptop', 'macbook', 'm3', 'portable'], 
  4.9, 
  234, 
  true, 
  true, 
  (SELECT id FROM public.profiles WHERE role = 'admin' LIMIT 1), 
  NOW(), 
  NOW()
),
(
  gen_random_uuid(), 
  'Sony WH-1000XM5', 
  'Industry-leading noise-canceling headphones with 30-hour battery life and exceptional sound quality.',
  45999, 
  49999, 
  'Electronics', 
  'Audio', 
  'Sony', 
  '/placeholder.svg', 
  35, 
  'SWH1000XM5', 
  ARRAY['headphones', 'noise-canceling', 'wireless', 'premium'], 
  4.8, 
  312, 
  false, 
  true, 
  (SELECT id FROM public.profiles WHERE role = 'admin' LIMIT 1), 
  NOW(), 
  NOW()
);

-- Fashion Products
INSERT INTO public.products (
  id, name, description, price, original_price, category, subcategory, brand, 
  main_image, stock_quantity, sku, tags, rating, review_count, is_featured, is_active, vendor_id, created_at, updated_at
) VALUES 
(
  gen_random_uuid(), 
  'Nike Air Max 270', 
  'Comfortable running shoes with Air Max technology. Perfect for daily wear and light workouts.',
  15999, 
  17999, 
  'Fashion', 
  'Shoes', 
  'Nike', 
  '/placeholder.svg', 
  45, 
  'NAM270-BLK', 
  ARRAY['shoes', 'running', 'comfortable', 'sports'], 
  4.6, 
  189, 
  false, 
  true, 
  (SELECT id FROM public.profiles WHERE role = 'admin' LIMIT 1), 
  NOW(), 
  NOW()
),
(
  gen_random_uuid(), 
  'Levi\'s 501 Original Jeans', 
  'Classic straight-fit jeans in authentic denim. Timeless style that never goes out of fashion.',
  8999, 
  9999, 
  'Fashion', 
  'Clothing', 
  'Levi\'s', 
  '/placeholder.svg', 
  67, 
  'L501-BLU-32', 
  ARRAY['jeans', 'denim', 'classic', 'casual'], 
  4.5, 
  276, 
  false, 
  true, 
  (SELECT id FROM public.profiles WHERE role = 'admin' LIMIT 1), 
  NOW(), 
  NOW()
),
(
  gen_random_uuid(), 
  'Ray-Ban Aviator Classic', 
  'Iconic aviator sunglasses with UV400 protection. Timeless design for any occasion.',
  12999, 
  14999, 
  'Fashion', 
  'Accessories', 
  'Ray-Ban', 
  '/placeholder.svg', 
  23, 
  'RBAV-GLD', 
  ARRAY['sunglasses', 'aviator', 'classic', 'premium'], 
  4.7, 
  98, 
  true, 
  true, 
  (SELECT id FROM public.profiles WHERE role = 'admin' LIMIT 1), 
  NOW(), 
  NOW()
);

-- Home & Garden Products
INSERT INTO public.products (
  id, name, description, price, original_price, category, subcategory, brand, 
  main_image, stock_quantity, sku, tags, rating, review_count, is_featured, is_active, vendor_id, created_at, updated_at
) VALUES 
(
  gen_random_uuid(), 
  'Philips Hue Smart Bulb Starter Kit', 
  'Smart LED bulbs with 16 million colors. Control with your phone or voice assistant.',
  8999, 
  10999, 
  'Home', 
  'Lighting', 
  'Philips', 
  '/placeholder.svg', 
  28, 
  'PHH-KIT-3', 
  ARRAY['smart-home', 'led', 'color-changing', 'wifi'], 
  4.4, 
  145, 
  false, 
  true, 
  (SELECT id FROM public.profiles WHERE role = 'admin' LIMIT 1), 
  NOW(), 
  NOW()
),
(
  gen_random_uuid(), 
  'KitchenAid Stand Mixer', 
  'Professional stand mixer with 10 speeds and 5-quart bowl. Perfect for baking enthusiasts.',
  89999, 
  99999, 
  'Home', 
  'Kitchen', 
  'KitchenAid', 
  '/placeholder.svg', 
  15, 
  'KASM-5QT-RED', 
  ARRAY['mixer', 'kitchen', 'baking', 'professional'], 
  4.9, 
  203, 
  true, 
  true, 
  (SELECT id FROM public.profiles WHERE role = 'admin' LIMIT 1), 
  NOW(), 
  NOW()
),
(
  gen_random_uuid(), 
  'Dyson V15 Detect Cordless Vacuum', 
  'Powerful cordless vacuum with laser dust detection and 60-minute runtime.',
  129999, 
  139999, 
  'Home', 
  'Cleaning', 
  'Dyson', 
  '/placeholder.svg', 
  8, 
  'DVV15-ABSL', 
  ARRAY['vacuum', 'cordless', 'powerful', 'cleaning'], 
  4.8, 
  167, 
  false, 
  true, 
  (SELECT id FROM public.profiles WHERE role = 'admin' LIMIT 1), 
  NOW(), 
  NOW()
);

-- Beauty Products
INSERT INTO public.products (
  id, name, description, price, original_price, category, subcategory, brand, 
  main_image, stock_quantity, sku, tags, rating, review_count, is_featured, is_active, vendor_id, created_at, updated_at
) VALUES 
(
  gen_random_uuid(), 
  'La Mer Moisturizing Cream', 
  'Luxury moisturizing cream with Miracle Broth. Provides intense hydration and anti-aging benefits.',
  89999, 
  99999, 
  'Beauty', 
  'Skincare', 
  'La Mer', 
  '/placeholder.svg', 
  12, 
  'LMMC-50ML', 
  ARRAY['skincare', 'moisturizer', 'luxury', 'anti-aging'], 
  4.7, 
  89, 
  true, 
  true, 
  (SELECT id FROM public.profiles WHERE role = 'admin' LIMIT 1), 
  NOW(), 
  NOW()
),
(
  gen_random_uuid(), 
  'Dyson Airwrap Multi-Styler', 
  'Revolutionary hair styling tool that dries, curls, waves, and smooths hair without extreme heat.',
  159999, 
  169999, 
  'Beauty', 
  'Hair Care', 
  'Dyson', 
  '/placeholder.svg', 
  6, 
  'DAM-NI', 
  ARRAY['hair-styling', 'curling', 'drying', 'heat-protection'], 
  4.6, 
  134, 
  false, 
  true, 
  (SELECT id FROM public.profiles WHERE role = 'admin' LIMIT 1), 
  NOW(), 
  NOW()
);

-- Sports Products
INSERT INTO public.products (
  id, name, description, price, original_price, category, subcategory, brand, 
  main_image, stock_quantity, sku, tags, rating, review_count, is_featured, is_active, vendor_id, created_at, updated_at
) VALUES 
(
  gen_random_uuid(), 
  'Peloton Bike+', 
  'Premium indoor cycling bike with 24" HD rotating touchscreen and live classes.',
  299999, 
  319999, 
  'Sports', 
  'Fitness', 
  'Peloton', 
  '/placeholder.svg', 
  4, 
  'PBK-PLUS', 
  ARRAY['fitness', 'cycling', 'indoor', 'premium'], 
  4.8, 
  78, 
  true, 
  true, 
  (SELECT id FROM public.profiles WHERE role = 'admin' LIMIT 1), 
  NOW(), 
  NOW()
),
(
  gen_random_uuid(), 
  'Wilson Pro Staff Tennis Racket', 
  'Professional tennis racket used by top players. Perfect balance of power and control.',
  15999, 
  17999, 
  'Sports', 
  'Tennis', 
  'Wilson', 
  '/placeholder.svg', 
  32, 
  'WPS-97', 
  ARRAY['tennis', 'racket', 'professional', 'sports'], 
  4.5, 
  156, 
  false, 
  true, 
  (SELECT id FROM public.profiles WHERE role = 'admin' LIMIT 1), 
  NOW(), 
  NOW()
);

-- Books
INSERT INTO public.products (
  id, name, description, price, original_price, category, subcategory, brand, 
  main_image, stock_quantity, sku, tags, rating, review_count, is_featured, is_active, vendor_id, created_at, updated_at
) VALUES 
(
  gen_random_uuid(), 
  'Atomic Habits by James Clear', 
  'Transform your life with tiny changes that lead to remarkable results. Bestselling self-help book.',
  2999, 
  3499, 
  'Books', 
  'Self-Help', 
  'Avery', 
  '/placeholder.svg', 
  89, 
  'AH-JC-HC', 
  ARRAY['self-help', 'habits', 'productivity', 'bestseller'], 
  4.9, 
  2341, 
  true, 
  true, 
  (SELECT id FROM public.profiles WHERE role = 'admin' LIMIT 1), 
  NOW(), 
  NOW()
),
(
  gen_random_uuid(), 
  'The Psychology of Money by Morgan Housel', 
  'Timeless lessons on wealth, greed, and happiness. Essential reading for financial literacy.',
  2499, 
  2799, 
  'Books', 
  'Finance', 
  'Harriman House', 
  '/placeholder.svg', 
  67, 
  'TPM-MH-PB', 
  ARRAY['finance', 'psychology', 'money', 'education'], 
  4.7, 
  892, 
  false, 
  true, 
  (SELECT id FROM public.profiles WHERE role = 'admin' LIMIT 1), 
  NOW(), 
  NOW()
); 